### PR TITLE
Add glob support

### PR DESCRIPTION
**Pull request by zandaqo**
Allows use of glob patterns in `files` parameter of `.doclets.yml`.

### CODE REVIEW

**Comment by lipp** [comment]
:100: looks great! don't know why the tests fail right now...

**Comment by zandaqo** [comment]
@lipp I've fixed the style issue. Now it complains about some `.changeOwner` though I can't figure out how it's related to the changes I've made.

**Comment by lipp** [comment]
@zandaqo yeah that's strange. this has definitely nothing todo with your PR. My PR also fails because of changeOwner although tests work locally. During adding more verbose error assertions travis builds stalled :(
no idea why...
I'll trigger a re-rerun in some hours, maybe the stalling is due to some trouble with travis itself

**Comment by lipp** [comment]
anyhow i'll merge the PR today no matter what.

**Comment by lipp** [comment]
@zandaqo seems that the .changeOwner test is causing the trouble (if i remove it, travis works just fine)

**Comment by lipp** [comment]
@zandaqo maybe you can rebase from master? the changeOwner test is disabled for now. i'll look into this and readd it soon.

**Comment by zandaqo** [comment]
@lipp done. Can you re-run Travis on Node 4? To be sure it's something with Travis since other builds are passing.

**Comment by lipp** [comment]
:+1:

**Pull request merged**
