### PR TITLE
add(tools): Tool to check the output of a single repo

### PR DESCRIPTION
**Pull request by janmeier**
Very, very simple fix for https://github.com/lipp/doclets/issues/68

It's not a separate module, just a script in `bin/` which starts an express server, watches the directory for changes and tells the browser to reload via socket.io

### CODE REVIEW

**Comment by janmeier** [comment]
2 out of 3 builds are green - could you rerun https://travis-ci.org/lipp/doclets/jobs/141367666 (timeout)

This already helped me get sequelize docs ready for doclets - Once organization support is in place we should be good to switch :)

**Comment by lipp** [comment]
@janmeier 💯  thanks a lot!!! support for (public) orgs and repos is already online for some weeks :)
Let me know if it does not work for you!

**Comment by janmeier** [comment]
Sweet, didn't know that - It works perfect! :) https://doclets.io/sequelize/sequelize/doclets

**Comment by lipp** [comment]
💯 Great!

**Pull request merged**
